From mongo:7.0
#storing the js file in the docker-entrypoint-initdb.d directory will automatically execute the js file when the container is started for the first time and initialize the database with the required data
Copy *.js /docker-entrypoint-initdb.d/
